"""molpack — Packmol-grade molecular packing with Python bindings."""

from ._protocols import Handler, Restraint
from .molpack import (
    AboveGaussianRestraint,
    AbovePlaneRestraint,
    Angle,
    Axis,
    BelowGaussianRestraint,
    BelowPlaneRestraint,
    CenteringMode,
    ConflictingPeriodicBoxesError,
    ConstraintsFailedError,
    EmptyMoleculeError,
    InsideBoxRestraint,
    InsideCubeRestraint,
    InsideCylinderRestraint,
    InsideEllipsoidRestraint,
    InsideSphereRestraint,
    InvalidPBCBoxError,
    MaxIterationsError,
    Molpack,
    NoTargetsError,
    OutsideBoxRestraint,
    OutsideCubeRestraint,
    OutsideCylinderRestraint,
    OutsideEllipsoidRestraint,
    OutsideSphereRestraint,
    PackError,
    PackResult,
    ScriptJob,
    StepInfo,
    Target,
    load_script,
)

__all__ = [
    # Typed values
    "Angle",
    "Axis",
    "CenteringMode",
    # Restraints (14 Packmol kinds)
    "InsideBoxRestraint",
    "InsideCubeRestraint",
    "InsideSphereRestraint",
    "InsideEllipsoidRestraint",
    "InsideCylinderRestraint",
    "OutsideBoxRestraint",
    "OutsideCubeRestraint",
    "OutsideSphereRestraint",
    "OutsideEllipsoidRestraint",
    "OutsideCylinderRestraint",
    "AbovePlaneRestraint",
    "BelowPlaneRestraint",
    "AboveGaussianRestraint",
    "BelowGaussianRestraint",
    # Core
    "Target",
    "Molpack",
    "PackResult",
    "StepInfo",
    # Script loader (`.inp` input)
    "ScriptJob",
    "load_script",
    # Duck-type protocols
    "Handler",
    "Restraint",
    # Errors
    "PackError",
    "ConstraintsFailedError",
    "MaxIterationsError",
    "NoTargetsError",
    "EmptyMoleculeError",
    "InvalidPBCBoxError",
    "ConflictingPeriodicBoxesError",
]
