"""molpack — Packmol-grade molecular packing with Python bindings."""

from ._protocols import Handler, Restraint
from .molpack import (
    AbovePlaneRestraint,
    Angle,
    AnglePrior,
    Axis,
    BelowPlaneRestraint,
    CbmcGrow,
    CenteringMode,
    ConflictingPeriodicBoxesError,
    ConstraintsFailedError,
    EmptyMoleculeError,
    ExponentialPlane,
    ExponentialPoint,
    GaussianPlane,
    GaussianPoint,
    GenCanPack,
    InsideBoxRestraint,
    InsideSphereRestraint,
    IntraResidual,
    InvalidPBCBoxError,
    LatticeGrow,
    MaxIterationsError,
    NoTargetsError,
    OutsideSphereRestraint,
    PackError,
    Pipeline,
    ScriptJob,
    StageInfo,
    State,
    StepContext,
    StepInfo,
    TabulatedPlane,
    TabulatedPoint,
    Target,
    TorsionPrior,
    init_thread_pool,
    load_script,
    num_threads,
    rayon_enabled,
)
from .version import MOLRS_MINOR, check_molrs_version, version

__all__ = [
    # Typed values
    "Angle",
    "Axis",
    "CenteringMode",
    # Growth statistics inputs
    "TorsionPrior",
    "AnglePrior",
    # Restraints
    "InsideBoxRestraint",
    "InsideSphereRestraint",
    "OutsideSphereRestraint",
    "AbovePlaneRestraint",
    "BelowPlaneRestraint",
    # Group-level distribution-matching restraints
    "GaussianPlane",
    "GaussianPoint",
    "ExponentialPlane",
    "ExponentialPoint",
    "TabulatedPlane",
    "TabulatedPoint",
    # Core
    "Target",
    "GenCanPack",
    "CbmcGrow",
    "LatticeGrow",
    "Pipeline",
    "State",
    "IntraResidual",
    "StepInfo",
    "StageInfo",
    "StepContext",
    # Script loader (`.inp` input)
    "ScriptJob",
    "load_script",
    # Parallel evaluation (rayon)
    "rayon_enabled",
    "num_threads",
    "init_thread_pool",
    # Duck-type protocols
    "Handler",
    "Restraint",
    # Post-pack whole-system relaxation (LAMMPS via molpy)
    # Errors
    "PackError",
    "ConstraintsFailedError",
    "MaxIterationsError",
    "NoTargetsError",
    "EmptyMoleculeError",
    "InvalidPBCBoxError",
    "ConflictingPeriodicBoxesError",
    "MOLRS_MINOR",
    "check_molrs_version",
    "version",
]
