"""Type stubs for the molpack native extension (compiled from Rust via PyO3)."""

import os
from collections.abc import Sequence
from typing import Any, Protocol, Self

import numpy as np
from numpy.typing import NDArray

# ---------------------------------------------------------------------------
# Typed values
# ---------------------------------------------------------------------------

class Angle:
    ZERO: Angle
    @classmethod
    def from_degrees(cls, deg: float) -> Angle: ...
    @classmethod
    def from_radians(cls, rad: float) -> Angle: ...
    @property
    def degrees(self) -> float: ...
    @property
    def radians(self) -> float: ...
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...

class Axis:
    X: Axis
    Y: Axis
    Z: Axis

class CenteringMode:
    AUTO: CenteringMode
    CENTER: CenteringMode
    OFF: CenteringMode

# ---------------------------------------------------------------------------
# Restraints
# ---------------------------------------------------------------------------

class InsideBoxRestraint:
    def __init__(
        self,
        min: Sequence[float],
        max: Sequence[float],
        periodic: tuple[bool, bool, bool] = (False, False, False),
    ) -> None: ...
    def __repr__(self) -> str: ...

class InsideSphereRestraint:
    def __init__(self, center: Sequence[float], radius: float) -> None: ...
    def __repr__(self) -> str: ...

class OutsideSphereRestraint:
    def __init__(self, center: Sequence[float], radius: float) -> None: ...
    def __repr__(self) -> str: ...

class AbovePlaneRestraint:
    def __init__(self, normal: Sequence[float], distance: float) -> None: ...
    def __repr__(self) -> str: ...

class BelowPlaneRestraint:
    def __init__(self, normal: Sequence[float], distance: float) -> None: ...
    def __repr__(self) -> str: ...

# Built-in restraint union — accepted wherever a native `*Restraint` is
# expected. Custom duck-typed objects (see `Restraint` Protocol in the
# package root) are also accepted.
type BuiltinRestraint = (
    InsideBoxRestraint
    | InsideSphereRestraint
    | OutsideSphereRestraint
    | AbovePlaneRestraint
    | BelowPlaneRestraint
)

class _RestraintLike(Protocol):
    def f(
        self,
        x: tuple[float, float, float],
        scale: float,
        scale2: float,
    ) -> float: ...
    def fg(
        self,
        x: tuple[float, float, float],
        scale: float,
        scale2: float,
    ) -> tuple[float, tuple[float, float, float]]: ...

type AnyRestraint = BuiltinRestraint | _RestraintLike

# ---------------------------------------------------------------------------
# Target
# ---------------------------------------------------------------------------

class Target:
    def __init__(self, frame: Any, count: int) -> None: ...
    def with_name(self, name: str) -> Self: ...
    def with_restraint(self, restraint: AnyRestraint | object) -> Self: ...
    def with_atom_restraint(
        self, indices: Sequence[int], restraint: AnyRestraint | object
    ) -> Self: ...
    def with_perturb_budget(self, budget: int) -> Self: ...
    def with_centering(self, mode: CenteringMode) -> Self: ...
    def with_rotation_bound(
        self, axis: Axis, center: Angle, half_width: Angle
    ) -> Self: ...
    def fixed_at(self, position: Sequence[float]) -> Self: ...
    def with_orientation(self, orientation: tuple[Angle, Angle, Angle]) -> Self: ...
    @property
    def name(self) -> str | None: ...
    @property
    def natoms(self) -> int: ...
    @property
    def count(self) -> int: ...
    @property
    def elements(self) -> list[str]: ...
    @property
    def radii(self) -> list[float]: ...
    @property
    def is_fixed(self) -> bool: ...
    def __repr__(self) -> str: ...

# ---------------------------------------------------------------------------
# StepInfo & Handler
# ---------------------------------------------------------------------------

class StepInfo:
    @property
    def loop_idx(self) -> int: ...
    @property
    def max_loops(self) -> int: ...
    @property
    def phase(self) -> int: ...
    @property
    def total_phases(self) -> int: ...
    @property
    def molecule_type(self) -> int | None: ...
    @property
    def fdist(self) -> float: ...
    @property
    def frest(self) -> float: ...
    @property
    def improvement_pct(self) -> float: ...
    @property
    def radscale(self) -> float: ...
    @property
    def precision(self) -> float: ...
    @property
    def relaxer_acceptance(self) -> list[tuple[int, float]]: ...
    def __repr__(self) -> str: ...

class _HandlerLike(Protocol):
    def on_start(self, ntotat: int, ntotmol: int) -> None: ...
    def on_step(self, info: StepInfo) -> bool | None: ...
    def on_finish(self) -> None: ...

# ---------------------------------------------------------------------------
# Molpack & PackResult
# ---------------------------------------------------------------------------

class PackResult:
    @property
    def positions(self) -> NDArray[np.float64]: ...
    @property
    def frame(self) -> dict[str, Any]: ...
    @property
    def elements(self) -> list[str]: ...
    @property
    def converged(self) -> bool: ...
    @property
    def fdist(self) -> float: ...
    @property
    def frest(self) -> float: ...
    @property
    def natoms(self) -> int: ...
    def __repr__(self) -> str: ...

class Molpack:
    def __init__(self) -> None: ...
    def with_tolerance(self, tolerance: float) -> Self: ...
    def with_precision(self, precision: float) -> Self: ...
    def with_inner_iterations(self, n: int) -> Self: ...
    def with_init_passes(self, n: int) -> Self: ...
    def with_init_box_half_size(self, half_size: float) -> Self: ...
    def with_periodic_box(
        self, min: tuple[float, float, float], max: tuple[float, float, float]
    ) -> Self: ...
    def with_perturb_fraction(self, f: float) -> Self: ...
    def with_random_perturb(self, enabled: bool) -> Self: ...
    def with_perturb(self, enabled: bool) -> Self: ...
    def with_seed(self, seed: int) -> Self: ...
    def with_parallel_eval(self, enabled: bool) -> Self: ...
    def with_progress(self, enabled: bool) -> Self: ...
    def with_handler(self, handler: _HandlerLike | object) -> Self: ...
    def with_global_restraint(self, restraint: AnyRestraint | object) -> Self: ...
    def pack(self, targets: list[Target], max_loops: int = 200) -> PackResult: ...
    def __repr__(self) -> str: ...

# ---------------------------------------------------------------------------
# Script loader (`.inp` format)
# ---------------------------------------------------------------------------

class ScriptJob:
    """Output of :func:`load_script` — a packer pre-configured from a
    ``.inp`` script, plus its target list and output path.

    Supports both attribute access (``job.packer``) and tuple
    unpacking (``packer, targets, output, nloop = job``).
    """

    @property
    def packer(self) -> Molpack: ...
    @property
    def targets(self) -> list[Target]: ...
    @property
    def output(self) -> str: ...
    @property
    def nloop(self) -> int: ...
    def __len__(self) -> int: ...
    def __getitem__(self, idx: int) -> Any: ...
    def __repr__(self) -> str: ...

def load_script(path: str | os.PathLike[str]) -> ScriptJob:
    """Parse a molpack ``.inp`` script and lower it to a ready-to-run
    packer and target list.

    Relative paths inside the script (structure files, output) are
    resolved against the script's parent directory.
    """

# ---------------------------------------------------------------------------
# Exceptions
# ---------------------------------------------------------------------------

class PackError(RuntimeError): ...
class ConstraintsFailedError(PackError): ...
class MaxIterationsError(PackError): ...
class NoTargetsError(PackError): ...
class EmptyMoleculeError(PackError): ...
class InvalidPBCBoxError(PackError): ...
class ConflictingPeriodicBoxesError(PackError): ...
