"""Type stubs for the molpack native extension (compiled from Rust via PyO3)."""

import os
from collections.abc import Callable, Sequence
from typing import Any, Protocol, Self

import numpy as np
from numpy.typing import NDArray

# ---------------------------------------------------------------------------
# Typed values
# ---------------------------------------------------------------------------

class Angle:
    ZERO: Angle
    @classmethod
    def from_degrees(cls, deg: float) -> Angle: ...
    @classmethod
    def from_radians(cls, rad: float) -> Angle: ...
    @property
    def degrees(self) -> float: ...
    @property
    def radians(self) -> float: ...
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...

class Axis:
    X: Axis
    Y: Axis
    Z: Axis

class CenteringMode:
    AUTO: CenteringMode
    CENTER: CenteringMode
    OFF: CenteringMode

# ---------------------------------------------------------------------------
# Restraints
#
# Geometry is a molrs region (``molrs.core.Sphere``, ``Cuboid``, ``Parallelepiped``,
# ``HalfSpace``, ``Cylinder``, ``Ellipsoid``, ``Polyhedron``, ``SphereUnion``,
# or a ``&`` / ``|`` / ``~`` composition); molpack lifts it to "stay inside".
# There is no molpack geometric restraint class.
# ---------------------------------------------------------------------------

# Collective (distribution-matching) restraints — drive a species' aggregate
# spatial distribution toward a target profile rather than confining each atom.
class GaussianPlane:
    def __init__(
        self,
        normal: Sequence[float],
        offset: float,
        strength: float,
        mu: float,
        sigma: float,
    ) -> None: ...
    def __repr__(self) -> str: ...

class GaussianPoint:
    def __init__(
        self, center: Sequence[float], strength: float, mu: float, sigma: float
    ) -> None: ...
    def __repr__(self) -> str: ...

class ExponentialPlane:
    def __init__(
        self,
        normal: Sequence[float],
        offset: float,
        strength: float,
        lambda_: float,
    ) -> None: ...

class ExponentialPoint:
    def __init__(
        self, center: Sequence[float], strength: float, lambda_: float
    ) -> None: ...

class TabulatedPlane:
    def __init__(
        self,
        normal: Sequence[float],
        offset: float,
        strength: float,
        xs: Sequence[float],
        rho: Sequence[float],
    ) -> None: ...

class TabulatedPoint:
    def __init__(
        self,
        center: Sequence[float],
        strength: float,
        xs: Sequence[float],
        rho: Sequence[float],
    ) -> None: ...

class SelfSeparation:
    """Keep every pair of copies of one species at least ``d_min`` apart,
    centre to centre — the anti-clustering restraint."""

    def __init__(self, d_min: float, strength: float = 1.0) -> None: ...
    @property
    def d_min(self) -> float: ...
    def __repr__(self) -> str: ...

# Built-in restraint union — accepted wherever a native `*Restraint` is
# expected. Custom duck-typed objects (see `Restraint` Protocol in the
# package root) are also accepted.
type BuiltinRestraint = (
    GaussianPlane
    | GaussianPoint
    | ExponentialPlane
    | ExponentialPoint
    | TabulatedPlane
    | TabulatedPoint
    | SelfSeparation
)

class _RegionLike(Protocol):
    """Any molrs region object: it exports the ``molrs.RegionRef`` capsule."""

    def _ffi_regionref_capsule(self) -> object: ...

class _RestraintLike(Protocol):
    def f(
        self,
        x: tuple[float, float, float],
        scale: float,
        scale2: float,
    ) -> float: ...
    def fg(
        self,
        x: tuple[float, float, float],
        scale: float,
        scale2: float,
    ) -> tuple[float, tuple[float, float, float]]: ...

type AnyRestraint = BuiltinRestraint | _RegionLike | _RestraintLike

# ---------------------------------------------------------------------------
# Method selection / growth
# ---------------------------------------------------------------------------

class TorsionPrior:
    """Geometric torsion prior — the mandatory statistics input of growth."""

    @staticmethod
    def uniform() -> TorsionPrior: ...
    @staticmethod
    def template(kappa: float) -> TorsionPrior: ...
    @staticmethod
    def states(states: Sequence[tuple[float, float]]) -> TorsionPrior: ...
    @staticmethod
    def three_state_from_c_inf(c_inf: float, theta_rad: float) -> TorsionPrior: ...
    def __repr__(self) -> str: ...

class AnglePrior:
    """Placement-angle prior: ``template()`` (all-atom) or ``wlc*`` (CG)."""

    @staticmethod
    def template() -> AnglePrior: ...
    @staticmethod
    def wlc(kappa: float) -> AnglePrior: ...
    @staticmethod
    def wlc_from_c_inf(c_inf: float) -> AnglePrior: ...
    def __repr__(self) -> str: ...

# ---------------------------------------------------------------------------
# Target
# ---------------------------------------------------------------------------

class Target:
    def __init__(self, frame: Any, count: int) -> None: ...
    @staticmethod
    def fixed_from(result: State) -> Target: ...
    def with_name(self, name: str) -> Self: ...
    def with_mass(self, amu: float) -> Self: ...
    def with_restraint(self, restraint: AnyRestraint | object) -> Self: ...
    def with_atom_restraint(
        self, indices: Sequence[int], restraint: AnyRestraint | object
    ) -> Self: ...
    def with_radius(self, radius: float) -> Self: ...
    def with_atom_radius(self, indices: Sequence[int], radius: float) -> Self: ...
    def with_fscale(self, fscale: float) -> Self: ...
    def with_atom_fscale(self, indices: Sequence[int], fscale: float) -> Self: ...
    def with_short_radius(self, short_radius: float) -> Self: ...
    def with_atom_short_radius(
        self, indices: Sequence[int], short_radius: float
    ) -> Self: ...
    def with_short_radius_scale(self, scale: float) -> Self: ...
    def with_atom_short_radius_scale(
        self, indices: Sequence[int], scale: float
    ) -> Self: ...
    def with_special_bonds(self, table: Sequence[float]) -> Self: ...
    def with_hydrogens(self, indices: Sequence[int]) -> Self: ...
    def with_perturb_budget(self, budget: int) -> Self: ...
    def with_centering(self, mode: CenteringMode) -> Self: ...
    def with_rotation_bound(
        self, axis: Axis, center: Angle, half_width: Angle
    ) -> Self: ...
    def fixed_at(self, position: Sequence[float]) -> Self: ...
    def with_orientation(self, orientation: tuple[Angle, Angle, Angle]) -> Self: ...
    @property
    def name(self) -> str | None: ...
    @property
    def natoms(self) -> int: ...
    @property
    def count(self) -> int: ...
    @property
    def elements(self) -> list[str]: ...
    @property
    def radii(self) -> list[float]: ...
    @property
    def special_bonds(self) -> list[float]: ...
    @property
    def is_fixed(self) -> bool: ...
    def __repr__(self) -> str: ...

# ---------------------------------------------------------------------------
# StepInfo & Handler
# ---------------------------------------------------------------------------

class StageInfo:
    """Which stage of the run a callback came from. A single-stage run
    reports ``index == 0`` and ``total == 1``."""

    @property
    def index(self) -> int: ...
    @property
    def total(self) -> int: ...
    @property
    def name(self) -> str: ...
    def __repr__(self) -> str: ...

class StepInfo:
    @property
    def stage(self) -> StageInfo: ...
    @property
    def loop_idx(self) -> int: ...
    @property
    def max_loops(self) -> int: ...
    @property
    def phase(self) -> int: ...
    @property
    def total_phases(self) -> int: ...
    @property
    def molecule_type(self) -> int | None: ...
    @property
    def fdist(self) -> float: ...
    @property
    def frest(self) -> float: ...
    @property
    def f(self) -> float:
        """GENCAN objective at the user's radii (Packmol's ``fx``)."""
    @property
    def improvement_pct(self) -> float: ...
    @property
    def radscale(self) -> float: ...
    @property
    def precision(self) -> float: ...
    def __repr__(self) -> str: ...

class StepContext:
    """Callback-scoped guard over the live packing context.

    Valid only inside the ``on_step`` call it was passed to; any access
    afterwards raises ``RuntimeError``. Properties copy on access.
    """

    @property
    def positions(self) -> NDArray[np.float64]: ...
    @property
    def natoms(self) -> int: ...
    def __repr__(self) -> str: ...

# Handlers are duck-typed: the native extension looks up ``on_start`` /
# ``on_step`` / ``on_finish`` by name and skips the ones that are absent, so
# no structural Protocol can type them without over-constraining callers.
# See ``molpack.Handler`` (``_protocols.py``) for the documented contract.

# ---------------------------------------------------------------------------
# Engine entries & State
# ---------------------------------------------------------------------------

class IntraResidual:
    """Same-copy scored vs exempted minima (Å, minimum image).

    An empty class is ``float('inf')``. Nested on :class:`State` as
    ``result.intra.scored`` / ``.exempted``.
    """

    @property
    def scored(self) -> float: ...
    @property
    def exempted(self) -> float: ...
    def __repr__(self) -> str: ...

class State:
    @property
    def positions(self) -> NDArray[np.float64]: ...
    @property
    def degraded(self) -> int:
        """Times the growth solver relaxed its constructive hard-core
        guarantee (always 0 on the GENCAN path)."""
    @property
    def intra(self) -> IntraResidual:
        """Same-copy scored vs exempted minima (Å). Forwards the assembled
        residual; does not recompute from positions."""
    @property
    def frame(self) -> Any:
        """Topology-complete ``molrs.core.Frame``, ready to use directly.

        Replays each target's source-frame topology (bonds/angles/dihedrals/
        impropers, with indices offset per copy) onto the packed coordinates,
        regenerates ``id`` / ``mol_id``, and stamps ``frame.box`` from the
        periodic box (if one was declared via ``with_periodic_box``). Returns a
        genuine ``molrs.core.Frame`` (built via the user's installed ``molrs``),
        which is ``molpy.Frame`` too — there is one Frame class. Falls
        back to a coordinates-only ``atoms`` block for ``.inp`` script packing.
        Force fields are out of scope — merge them separately.
        """
        ...
    @property
    def elements(self) -> list[str]: ...
    @property
    def converged(self) -> bool: ...
    @property
    def fdist(self) -> float: ...
    @property
    def frest(self) -> float: ...
    @property
    def natoms(self) -> int: ...
    def __repr__(self) -> str: ...

# ---------------------------------------------------------------------------
# Script loader (`.inp` format)
# ---------------------------------------------------------------------------

class ScriptJob:
    """Output of :func:`load_script` — a :class:`GenCanPack` pre-configured
    from a ``.inp`` script, plus its target list and output path.

    Supports both attribute access (``job.packer``) and tuple
    unpacking (``packer, targets, output, nloop = job``).
    """

    @property
    def packer(self) -> GenCanPack: ...
    @property
    def targets(self) -> list[Target]: ...
    @property
    def output(self) -> str: ...
    @property
    def nloop(self) -> int: ...
    def __len__(self) -> int: ...
    def __getitem__(self, idx: int) -> Any: ...
    def __repr__(self) -> str: ...

def load_script(
    path: str | os.PathLike[str],
    *,
    read_frame: Callable[..., Any] | None = None,
) -> ScriptJob:
    """Parse a molpack ``.inp`` script and lower it to a ready-to-run
    packer and target list.

    Relative paths inside the script (structure files, output) are
    resolved against the script's parent directory.
    """

# ---------------------------------------------------------------------------
# Parallel evaluation (rayon)
# ---------------------------------------------------------------------------

def rayon_enabled() -> bool:
    """True if this wheel was built with the ``rayon`` feature (parallel
    evaluation compiled in)."""

def num_threads() -> int:
    """Worker threads the parallel evaluator will use — the rayon global pool
    size, or ``1`` for a serial build."""

def init_thread_pool(n: int) -> None:
    """Pin the rayon global thread pool to ``n`` workers.

    Must be called before the first parallel pack — the pool is immutable once
    built. Raises :class:`RuntimeError` without the ``rayon`` feature or if the
    pool was already initialized, and :class:`ValueError` if ``n < 1``. For a
    scaling sweep, set the count once per process and launch one process per
    data point.
    """

# ---------------------------------------------------------------------------
# Exceptions
# ---------------------------------------------------------------------------

class PackError(RuntimeError): ...
class ConstraintsFailedError(PackError): ...
class MaxIterationsError(PackError): ...
class NoTargetsError(PackError): ...
class EmptyMoleculeError(PackError): ...
class InvalidPBCBoxError(PackError): ...

class GenCanPack:
    """Rigid-body GENCAN packing entry (engine-entry-split). One engine, one run."""

    def __init__(self) -> None: ...
    def with_restart(self, result: State) -> Self:
        """Continue on a previous run's placement solution (the explicit
        push-off chain): the free copies start exactly where ``result``
        left them; the cell travels with the seed — do not declare a box,
        density, or cell on a seeded engine."""
        ...
    def with_tolerance(self, tolerance: float) -> Self: ...
    def with_precision(self, precision: float) -> Self: ...
    def with_seed(self, seed: int) -> Self: ...
    def with_periodic_box(self, min: Sequence[float], max: Sequence[float]) -> Self: ...
    def with_density(self, rho: float) -> Self: ...
    def with_progress(self, on: bool = True) -> Self: ...
    def with_log_level(self, level: str) -> Self:
        """``"quiet"`` / ``"summary"`` / ``"progress"`` / ``"verbose"``;
        an explicit level wins over :meth:`with_progress`."""
        ...
    def with_log_frequency(self, n: int) -> Self: ...
    def with_parallel_eval(self, enabled: bool) -> Self: ...
    def with_global_restraint(self, restraint: AnyRestraint | object) -> Self: ...
    def with_handler(self, handler: object) -> Self: ...
    def with_inner_iterations(self, n: int) -> Self: ...
    def with_init_passes(self, n: int) -> Self: ...
    def with_init_box_half_size(self, half_size: float) -> Self: ...
    def with_perturb(
        self, fraction: float, random: bool = False, enabled: bool = True
    ) -> Self: ...
    def with_avoid_overlap(self, on: bool = True) -> Self: ...
    def with_early_stop(
        self,
        enabled: bool = True,
        *,
        threshold_pct: float = 10.0,
        patience: int = 10,
    ) -> Self:
        """End a GENCAN phase once, at the user's radii (``radscale == 1``),
        Packmol's ``bestf`` has improved by less than ``threshold_pct``
        percent over ``patience`` loops. On by default (10 % is Packmol's
        movebad threshold); ``enabled=False`` runs every phase to
        ``max_loops`` as Packmol does. A stopped final phase leaves
        ``State.converged`` false."""
    def run(self, targets: Sequence[Target], max_loops: int | None = None) -> State:
        """``max_loops`` defaults to Packmol's ``nloop``: ``200 * len(targets)``."""

class CbmcGrow:
    """Configurational-bias chain-growth entry. The torsion prior is
    mandatory; no hidden push-off — chain
    ``GenCanPack().with_restart(result)`` explicitly."""

    def __init__(self, torsion_prior: TorsionPrior) -> None: ...
    def with_tolerance(self, tolerance: float) -> Self: ...
    def with_precision(self, precision: float) -> Self: ...
    def with_seed(self, seed: int) -> Self: ...
    def with_periodic_box(self, min: Sequence[float], max: Sequence[float]) -> Self: ...
    def with_density(self, rho: float) -> Self: ...
    def with_progress(self, on: bool = True) -> Self: ...
    def with_log_level(self, level: str) -> Self:
        """``"quiet"`` / ``"summary"`` / ``"progress"`` / ``"verbose"``;
        an explicit level wins over :meth:`with_progress`."""
        ...
    def with_log_frequency(self, n: int) -> Self: ...
    def with_parallel_eval(self, enabled: bool) -> Self: ...
    def with_global_restraint(self, restraint: AnyRestraint | object) -> Self: ...
    def with_handler(self, handler: object) -> Self: ...
    def with_trials(self, trials: int) -> Self: ...
    def with_retract(self, steps: int) -> Self: ...
    def with_relax(self, every: int, window: int) -> Self: ...
    def with_selectivity(self, beta: float) -> Self: ...
    def with_soften_after(self, attempts: int) -> Self: ...
    def with_min_hard_scale(self, scale: float) -> Self: ...
    def with_angle_prior(self, prior: AnglePrior) -> Self: ...
    def with_soft_shell(self, width: float) -> Self: ...
    def with_serial(self, serial: bool = True) -> Self: ...
    def with_void_bias(self, void_bias: bool = True) -> Self: ...
    def run(self, targets: Sequence[Target], max_loops: int) -> State: ...

class LatticeGrow:
    """Diamond-lattice growth entry: melt-density chain generation as an
    on-lattice SAW (RIS-weighted, self-avoiding), decorated back to the
    template's exact bonded geometry. Residual contacts are reported
    honestly — chain ``GenCanPack().with_restart(result)`` for the push-off.
    Shares the engine builders (tolerance, seed, box/density, handlers)."""

    def __init__(self, torsion_prior: TorsionPrior) -> None: ...
    def with_tolerance(self, tolerance: float) -> Self: ...
    def with_precision(self, precision: float) -> Self: ...
    def with_seed(self, seed: int) -> Self: ...
    def with_periodic_box(self, min: Sequence[float], max: Sequence[float]) -> Self: ...
    def with_density(self, rho: float) -> Self: ...
    def with_progress(self, on: bool = True) -> Self: ...
    def with_log_level(self, level: str) -> Self: ...
    def with_log_frequency(self, n: int) -> Self: ...
    def with_parallel_eval(self, enabled: bool) -> Self: ...
    def with_global_restraint(self, restraint: AnyRestraint | object) -> Self: ...
    def with_handler(self, handler: object) -> Self: ...
    def with_occupancy_guard(self, on: bool = True) -> Self: ...
    def run(self, targets: Sequence[Target], max_loops: int) -> State: ...

StageEntry = GenCanPack | CbmcGrow | LatticeGrow
"""The entry objects a :class:`Pipeline` accepts as a stage — this stub's
mirror of the extension's single ``stage_entry_registry!`` table."""

class Pipeline:
    """A sequence of stages behind one lifecycle, one settings set and one
    handler set.

    The shared knobs are the run's — declare them here, not on a stage. A
    stage's own handlers travel with it and are *adopted*: they observe the
    whole run. A stage carrying a non-default shared knob is refused by
    name (``ValueError``) at :meth:`run`, never silently stripped, and an
    object that is not an entry raises ``TypeError`` where it is handed
    over.
    """

    def __init__(self, stages: Sequence[StageEntry] | None = None) -> None: ...
    def with_stage(self, stage: StageEntry) -> Self: ...
    def with_tolerance(self, tolerance: float) -> Self: ...
    def with_precision(self, precision: float) -> Self: ...
    def with_seed(self, seed: int) -> Self: ...
    def with_periodic_box(self, min: Sequence[float], max: Sequence[float]) -> Self: ...
    def with_density(self, rho: float) -> Self: ...
    def with_progress(self, on: bool = True) -> Self: ...
    def with_log_level(self, level: str) -> Self:
        """``"quiet"`` / ``"summary"`` / ``"progress"`` / ``"verbose"``;
        an explicit level wins over :meth:`with_progress`."""
        ...
    def with_log_frequency(self, n: int) -> Self: ...
    def with_parallel_eval(self, enabled: bool) -> Self: ...
    def with_global_restraint(self, restraint: AnyRestraint | object) -> Self: ...
    def with_handler(self, handler: object) -> Self: ...
    def run(self, targets: Sequence[Target], max_loops: int) -> State: ...
    def __repr__(self) -> str: ...
